"""add border ports and wait times

Revision ID: 1b5b382d9af0
Revises: 85a7ad8991ad
Create Date: 2026-07-09 16:52:36.704811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b5b382d9af0'
down_revision: Union[str, Sequence[str], None] = '85a7ad8991ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('border_ports', 'commercial_automation_type')
    op.drop_column('border_ports', 'date')
    op.drop_column('border_ports', 'crossing_name')
    op.add_column('wait_times', sa.Column('primary_lane_type', sa.Enum('COMMERCIAL_LANE', 'VEHICLE_LANE', 'PEDESTRIAN_LANE', name='primarylanetype', native_enum=False), nullable=True))
    op.add_column('wait_times', sa.Column('secondary_lane_type', sa.Enum('STANDARD_LANE', 'READY_LANE', 'NEXUS_LANE', 'FAST_LANE', name='secondarylanetype', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wait_times', 'secondary_lane_type')
    op.drop_column('wait_times', 'primary_lane_type')
    op.add_column('border_ports', sa.Column('crossing_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('border_ports', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('border_ports', sa.Column('commercial_automation_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
