"""link wait times to border ports

Revision ID: 4a1b4158f522
Revises: 1b5b382d9af0
Create Date: 2026-07-09 16:58:05.933194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a1b4158f522'
down_revision: Union[str, Sequence[str], None] = '1b5b382d9af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wait_times', sa.Column('border_port_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_wait_times_border_port_id'), 'wait_times', ['border_port_id'], unique=False)
    op.create_foreign_key(None, 'wait_times', 'border_ports', ['border_port_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wait_times', type_='foreignkey')
    op.drop_index(op.f('ix_wait_times_border_port_id'), table_name='wait_times')
    op.drop_column('wait_times', 'border_port_id')
    # ### end Alembic commands ###
