"""store wait update time as timestamp

Revision ID: 610fa046f8d5
Revises: 4a1b4158f522
Create Date: 2026-07-09 17:28:15.352950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '610fa046f8d5'
down_revision: Union[str, Sequence[str], None] = '4a1b4158f522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        """
        UPDATE wait_times
        SET update_time = NULL
        WHERE update_time IS NULL
           OR update_time = ''
           OR update_time = 'N/A'
           OR update_time !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}([ T].*)?$'
        """
    )
    op.alter_column(
        'wait_times',
        'update_time',
        existing_type=sa.VARCHAR(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        postgresql_using='update_time::timestamp with time zone',
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wait_times', 'update_time',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
